#!/bin/bash
# *NOTE* Change these based on 
ASSIMP_DIR=../assimp
API=24
# ARCH arm arm64 x86 x86_64
ARCH=arm
# ARCH armeabi-v7a arm64-v8a x86 x86_64
ARCH_ABI=armeabi-v7a
OUTPUT_DIR=../assimp-build-$ARCH
ANDROID_PATH=/Users/makai/Library/Android/sdk
NDK_PATH=/Users/makai/Library/Android/sdk/ndk-bundle
NDK_TOOLCHAIN=../android-toolchain-$API-llvm-$ARCH
CMAKE_TOOLCHAIN=$NDK_PATH/build/cmake/android.toolchain.cmake
CMAKE_PATH=$ANDROID_PATH/cmake/3.10.2.4988404

echo $ASSIMP_DIR
echo $API
echo $ARCH
echo $ARCH_ABI
echo $OUTPUT_DIR
echo $ANDROID_PATH
echo $NDK_PATH
echo $NDK_TOOLCHAIN
echo $CMAKE_TOOLCHAIN
echo $CMAKE_PATH

rm -rf $NDK_TOOLCHAIN
echo $(python $NDK_PATH/build/tools/make_standalone_toolchain.py --arch=$ARCH --stl=libc++ --api=$API --install-dir=$NDK_TOOLCHAIN)

# *NOTE* Careful if you don't want rm -rf, I use it for testing purposes.
rm -rf $OUTPUT_DIR
mkdir $OUTPUT_DIR

# pushd doesn't seem to work ):<
cd $OUTPUT_DIR

$PATH=$CMAKE_PATH/bin;$ANDROID_PATH/tools;$ANDROID_PATH/platform-tools;$PATH

#cmake -GNinja -DCMAKE_TOOLCHAIN_FILE=$CMAKE_TOOLCHAIN -DASSIMP_ANDROID_JNIIOSYSTEM=ON -DANDROID_NDK=$NDK_PATH -DCMAKE_MAKE_PROGRAM=$CMAKE_PATH/bin/ninja -DCMAKE_BUILD_TYPE=Release -DANDROID_ABI="$ARCH_ABI" -DANDROID_NATIVE_API_LEVEL=$API -DANDROID_FORCE_ARM_BUILD=TRUE -DCMAKE_INSTALL_PREFIX=install -DANDROID_STL=c++_shared -DCMAKE_CXX_FLAGS=-Wno-c++11-narrowing -DANDROID_TOOLCHAIN=clang -DASSIMP_BUILD_TESTS=OFF $ASSIMP_DIR
#cmake --build .

cmake -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_TOOLCHAIN -DCMAKE_INSTALL_PREFIX=/assimp -DANDROID_ABI=$ARCH_ABI -DANDROID_NATIVE_API_LEVEL=android-$API -DANDROID_FORCE_ARM_BUILD=TRUE -DANDROID_STL=c++_shared -DASSIMP_BUILD_OBJ_IMPORTER=TRUE -DASSIMP_BUILD_FBX_IMPORTER=TRUE -DANDROID_NDK=$NDK_PATH -DCMAKE_BUILD_TYPE=Release -DANDROID_FORCE_ARM_BUILD=TRUE -DCMAKE_CXX_FLAGS=-Wno-c++11-narrowing -DANDROID_TOOLCHAIN=clang -DASSIMP_BUILD_TESTS=OFF -DASSIMP_NO_EXPORT=FALSE -DASSIMP_BUILD_ASSIMP_TOOLS=TRUE -DASSIMP_BUILD_SAMPLES=FALSE -DASSIMP_BUILD_ALL_IMPORTERS_BY_DEFAULT=TRUE $ASSIMP_DIR
make -j8

